// Lightweight venue name lookup for DiscoveryPanel (client-side)
// Mirrors venueType keys from convex/matchingUtils.ts
export const VENUE_SUGGESTIONS: Record<string, { name: string }> = {
  music_studio: { name: "The Jam Spot" },
  outdoor_court: { name: "Potrero Hill Rec Center" },
  trailhead: { name: "Lands End Trail" },
  outdoor_park: { name: "Dolores Park" },
  climbing_gym: { name: "Mission Cliffs" },
  private_home: { name: "Hayes Valley Home" },
  cafe: { name: "City Lights Books area" },
  bar_lounge: { name: "The Interval" },
  art_studio: { name: "Hayes Valley Art Gallery" },
  gallery: { name: "Hayes Valley Art Gallery" },
  studio: { name: "Mission Yoga" },
  outdoor_neighborhood: { name: "North Beach" },
  coworking_space: { name: "Spark Social SF" },
  makerspace: { name: "Noisebridge" },
  bookstore: { name: "City Lights Books" },
  music_venue: { name: "SF Community Music Center" },
  dance_studio: { name: "Mission Dance Studio" },
  beach: { name: "Ocean Beach" },
  skatepark: { name: "SoMa Skatepark" },
  community_garden: { name: "Sunset Community Garden" },
  food_hall: { name: "Spark Social SF" },
  restaurant: { name: "Castro Restaurant" },
  rooftop_lounge: { name: "NEMA Rooftop" },
  rec_center: { name: "Potrero Hill Rec Center" },
  community_kitchen: { name: "Rainbow Grocery area" },
  community_space: { name: "The Bindery" },
  outdoor_field: { name: "GGP Polo Fields" },
};
